Make sure table border can be seen in mozilla
tidepool-org/blip pull request #1148
Opened 2022-11-17 19:57 UTC by ginnyyadav

Went down this rabbit hole  and seems to be an issue specifically with Mozilla Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=688556 
 
background-clip: padding-box seems to fix the issue.

2022-11-18 18:31 UTC, clintonium-119 requested changes
Just a couple of tiny change requests.  Just non-breaking nits.

2022-11-18 18:31 UTC, clintonium-119 commented on app/components/elements/Table.js
> +    background-clip: padding-box
```suggestion
    background-clip: padding-box;
```
Should always have a semicolon after style declarations.  No harm here, but any subsequent styles added would be ignored.

2022-11-18 18:31 UTC, clintonium-119 commented on app/components/elements/Table.js
> +
```suggestion
```
Suggest cleaning up this extra line that was added

2022-11-19 14:19 UTC, ginnyyadav commented
Thanks @clintonium-119 good catches 🙏

2022-12-01 17:15 UTC, clintonium-119 approved these changes
LGTM :)

2022-12-02 14:47 UTC, merged