[WEB-2477] add mrn/ehr settings api and form validation
tidepool-org/blip pull request #1277
Opened 2023-08-18 21:33 UTC by krystophv

2023-08-22 15:14 UTC, clintonium-119 requested changes
Just one small translation key suggestion that I _think_ we need before approval.  Otherwise, looks great :+1:

2023-08-22 17:05 UTC, krystophv commented on app/components/clinic/PatientForm.js
> +          label={t(mrnSettings?.required ? 'MRN' : 'MRN (optional)')}
Ah yeah, even if it _did_ work, it'd almost certainly be inviting some sort of edge case behavior. Good call 👍🏼

2023-08-22 20:18 UTC, clintonium-119 approved these changes
LGTM :shipit:

2023-10-20 20:56 UTC, krystophv commented
Supplanted by https://github.com/tidepool-org/blip/pull/1289

2023-10-20 20:56 UTC, closed without merging