[WEB-2595] Critical depandancy updates
tidepool-org/blip pull request #1313
Opened 2023-11-23 19:39 UTC by clintonium-119

[WEB-2595]

2023-12-20 16:28 UTC, krystophv requested changes
Just about everything looks good. I'd like to avoid breaking cross-platform compatibility by introducing a bash script for development, though.

2024-01-08 16:42 UTC, clintonium-119 commented on artifact.test.sh
Ah yeah, this slipped into VC accidentally at some point in the past.  Removing

2024-01-08 17:10 UTC, clintonium-119 commented on package.json
> +    "startLocal": "./config/startLocal.sh",
I'll revert this.  I hadn't wanted to do it either, but I had changed it to allow it to still run with `yarn startLocal`.
There are some changes in the latest yarn which cause it to error.

Using `npm run startLocal` still works fine, though, and will work for Windows (well, if it ever worked for Windows - I've never tested it)

2024-01-08 17:13 UTC, clintonium-119 commented on config/startLocal.sh
Reverted

2024-01-08 20:54 UTC, krystophv approved these changes
Updates LGTM 🚀

2024-01-18 19:35 UTC, clintonium-119 commented
/deploy qa1

2024-01-25 14:20 UTC, clintonium-119 commented
/deploy dev

2024-04-16 12:37 UTC, merged