[WEB-60] Print Date Range UI
tidepool-org/blip pull request #809
Opened 2020-09-09 22:52 UTC by thacherT1D

Jira Ticket - https://tidepool.atlassian.net/browse/WEB-60

2020-09-17 17:40 UTC, cbwebdevelopment requested changes
It's a solid start.  Most of the logic is on point -- but we should probably make sure the dates set are fully-inclusive (i.e start of the day for the startDate, end of the day for the endDate) and respective of the user's timezone.

When possible, we should leverage the rebass styling props over the generic `style` prop.  I have a few other theming/markup suggestions within the comments.

As discussed, with you being off for a vacay, I'll pick up on this and implement my suggested changes, and then pass it off for a second round of PR reviews

2020-09-17 17:40 UTC, cbwebdevelopment commented on app/components/PrintDateRangeModal.js
> +          isOutsideRange={day => (moment().diff(day) < 0)}
Can probably set the minWidth and minHeight properties here, and only set the minHeight when the datepicker is open to match the Figma spec

```suggestion
          isOutsideRange={day => (moment().diff(day) < 0)}
          themeProps={{
            minWidth: '580px',
            minHeight: datePickerOpen ? '300px' : undefined,
          }}
```

Note: you'll need to implement `datePickerOpen` state for this to work

2020-09-17 17:40 UTC, cbwebdevelopment commented on app/components/PrintDateRangeModal.js
> +          </Flex>
No need for wrapping `Flex` component here, and caption should be given error color
```suggestion
          <Caption mt={2} color="feedback.danger">
            Please select a date range
          </Caption>
```

2020-09-17 17:40 UTC, cbwebdevelopment commented on stories/PrintDateRangeModal.stories.js
> +        'https://www.figma.com/file/iuXkrpuLTXExSnuPJE3Jtn/Tidepool-Design-System---Sprint-1?node-id=8%3A826',
Figma link should be updated.  Pointing to the `Dialog` component spec currently

2020-09-17 20:51 UTC, cbwebdevelopment commented on app/components/PrintDateRangeModal.js
> +    startDate: moment().subtract(startDate, 'days'),
Implemented

2020-09-17 20:53 UTC, cbwebdevelopment commented
@krystophv I did the initial PR review for @thacherT1D on this, but since she's away for a couple of weeks, I implemented my suggested changes and marked them as resolved.

Just passing to you now for a final review.

2020-09-17 21:13 UTC, krystophv approved these changes
LGTM 🚢

2020-09-18 13:15 UTC, cbwebdevelopment approved these changes

2020-09-18 13:15 UTC, merged