[WEB-836] [WEB-1011] [WEB-991] [WEB-1133] new clinic admin interface basics
tidepool-org/blip pull request #900
Opened 2021-05-17 20:08 UTC by krystophv

This should take care of [WEB-836] [WEB-1011] [WEB-991] and [WEB-1133]. 
Includes the clinic administration landing page, modifications to clinic account creation, clinician inviting and deleting of invites, deleting and editing clinicians and all associated API linkages.

Pairs with https://github.com/tidepool-org/platform-client/pull/120

2021-05-21 14:14 UTC, cbwebdevelopment requested changes
Great job on this!  I do have a bunch of change suggestions, but they almost all fall into one of two categories:

1. Missing translatability wrappers on text
2. Super nit-picky formatting suggestions for consistency (can be ignored)

Aside from this, there were just a couple of instances (captured in comments) where I think we need to respond less optimistically to async requests.

Really a stellar job on this.  Incredibly thorough, and brought to my attention some nice new patterns for handling redux state and route dispatches.  Love it 💯 

I can't say I enjoyed looking over that many lines of test code, but at least I didn't have to write them ;P

2021-05-21 17:43 UTC, krystophv commented on app/components/elements/Button.js
> +    'danger',
Ah yeah, didn't catch that in the merge.

2021-05-21 17:45 UTC, krystophv commented on app/pages/clinicianedit/clinicianedit.js
> +      </Body1>
I honestly don't remember re: the spaces. I'll remove them.

2021-05-24 16:37 UTC, krystophv commented on app/pages/clinicadmin/clinicadmin.js
> +  const renderMore = ({ ...props }) => {
I don't believe so. I'll just switch it out.

2021-05-24 16:57 UTC, krystophv commented on app/pages/clinicianedit/clinicianedit.js
> +    dispatch(push('/clinic-admin'));
Yeah, that's a good call - I'll move the updateClinician toast tracking and redirect on success.

2021-05-24 17:08 UTC, krystophv commented on app/redux/actions/async.js
> +        dispatch(push('/clinic-admin'));
I'd generally agree, but we have a somewhat established pattern of doing the redirects in actions, especially for key actions in signup/setup flows.

2021-05-25 14:34 UTC, cbwebdevelopment commented on app/redux/actions/async.js
> +        dispatch(push('/clinic-admin'));
Ok. Let's leave this as-is, then.

I've looked over all the other changes you've pushed.  This seems to be the last item, so if you re-request a review I'm good to approve.

2021-05-25 15:25 UTC, cbwebdevelopment approved these changes
Great work on this :)
Approved.

2021-05-25 20:15 UTC, merged