[WEB-880] clinic signup and administration
tidepool-org/blip pull request #923
Opened 2021-07-23 18:23 UTC by cbwebdevelopment

See [WEB-880]

2021-07-27 23:22 UTC, krystophv submitted a review, later dismissed
Edit: I read a bot comment and thought this was ready for review when it's still in progress, my bad.

2021-08-11 15:06 UTC, cbwebdevelopment commented
/deploy dev

2021-08-23 22:36 UTC, krystophv requested changes
Excellent (and huge) work overall. Couple of small edits to make.

2021-08-24 14:45 UTC, cbwebdevelopment commented on test/unit/components/navbar/NavigationMenu.test.js
> +      menuOptions.at(2).simulate('click');
Yep. Removing.

2021-08-24 14:48 UTC, cbwebdevelopment commented on test/unit/pages/patients.test.js
> +    // });
Removing this. This was for when the plan was to re-use the patients view as part of the clinic workspace.

2021-08-24 15:25 UTC, cbwebdevelopment commented
@krystophv All feedback has been addressed

2021-08-24 15:29 UTC, krystophv approved these changes
LGTM 🚀

2021-08-24 15:31 UTC, merged